server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/venturenix_ol?useSSL=false
    username: oscarlo
    password: oscarVenturenixLab2023.
  # spring:
  #   datasource:
  #     url: jdbc:mysql://projectol-database-1.ctcmiocmq3o5.ap-southeast-1.rds.amazonaws.com:3306/venturenix_ol?useSSL=false
  #     username: projectOLadmin
  #     password: projectOL
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        # hbm2ddl:
        #   import_files: /resources/data.sql
    hibernate:
      ddl-auto: update

# App Properties
bezkoder:
  app:
    jwtSecret: ======================BezKoder=Spring===========================
    jwtExpirationMs: 86400000
